apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: test
  name: spring-boot-postgres-sample
  namespace: default
  resourceVersion: "149358"
  uid: e45611d1-5222-4a2a-8d59-d8bf16eb08c7
spec:
  clusterIP: 10.104.39.249
  clusterIPs:
  - 10.104.39.249
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31835
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-postgres-sample
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer:
    ingress:
    - hostname: localhost
