apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: test
  name: spring-boot-postgres-sample
  namespace: default
spec:
  clusterIP: 10.104.39.249
  clusterIPs:
  - 10.104.39.249
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31835
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot-postgres-sample
  sessionAffinity: None
  type: NodePort
