apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-postgres-sample
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: spring-boot-postgres-sample
      labels:
        app: spring-boot-postgres-sample
  selector:
    matchLabels:
      app: spring-boot-postgres-sample
    spec:
      containers:
      - name: spring-boot-postgres-sample
        env:
          - name: POSTGRES_USER
            value: testpostgre
          - name: POSTGRES_PASSWORD
            value: asalaja
          - name: POSTGRES_HOST
            value: url=jdbc:postgresql://testpostgre/postgres
        image: erwiinsaputra/spring-boot-postgres-on-k8s:v1
